global:
  scrape_interval: 5s 

scrape_configs:
  - job_name: 'ml_model_exporter' # Nama job disesuaikan biar mirip patokan
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5001']